[mypy]
python_version = 3.14
mypy_path = src
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
ignore_missing_imports = True
follow_imports = skip

[mypy-PyQt6.*]
ignore_missing_imports = True
